대기 주문 목록 ver.2
vanillacake369/sparta-team-kiosk pull request #18
Opened 2023-10-27 08:38 UTC by BMDK9

2023-10-27 08:40 UTC, BMDK9 commented on src/domain/order/service/store/HandleWaitingOrder.java
> +                        // orders.get(handleNumber - 1); 를 완료 주문으로 보낸다. 어디로 보내야하지??
이거 어디로 어떻게 보내야할지 확신이 없어서 미완으로 남겼습니다.

2023-10-27 08:43 UTC, BMDK9 commented on src/domain/order/service/store/HandleWaitingOrder.java
> +                        // orders.get(handleNumber - 1); 를 완료 주문으로 보낸다. 어디로 보내야하지??
아 추가로 제가 이해한 대로라면 이 기능을 완료하면
orders 배열에서 해당 주문을 삭제시켜야하는거 맞죠??

2023-10-27 08:56 UTC, BMDK9 commented on src/domain/order/service/store/HandleWaitingOrder.java
> +                        orders.remove(handleNumber-1); // 완료 처리한 주문은 대기 주문 목록에서 삭제한다.
이거 어디로 어떻게 보내야할지 확신이 없어서 미완으로 남겼습니다.
아 추가로 제가 이해한 대로라면 case 1을 완료하면
orders 배열에서 해당 주문을 삭제시켜야하는거 맞죠??

2023-10-28 05:57 UTC, vanillacake369 requested changes
굉장히 코딩을 많이 하셨네요!
1. 주석을 많이 달아주셔서 좋았고
2. 로직 프로세싱도 잘 하셨고
3. 의문이 있으신 부분에 comment 남겨주셔서 좋았습니다!

다만
기능구현에 따른 커밋 메세지와 PR메세지를 남겨주시지 않아 무엇을 구현했는지 확인해야했네요!

혹시 comment 사항에 대해 고려해보시겠어요~?

2023-10-28 05:57 UTC, vanillacake369 commented on src/domain/order/service/store/HandleWaitingOrder.java
> +            } else if (handleNumber != 0) {     // 주문 번호 0번을 입력하지 않았을 때
여기서 주문 번호가 아닌 입력이 들어온 경우를 확인해서 예외를 처리하는 건 어떨까요??

2023-10-28 05:57 UTC, vanillacake369 commented on src/domain/order/service/store/HandleWaitingOrder.java
> +            } else if (handleNumber != 0) {     // 주문 번호 0번을 입력하지 않았을 때
맨 아래에 default 문을 사용하는 것보다 입력에 대한 검증을 먼저 하는 게 좋지 않을까요?

2023-10-28 05:57 UTC, vanillacake369 commented on src/domain/order/service/store/HandleWaitingOrder.java
> +                        orders.remove(handleNumber-1); // 완료 처리한 주문은 대기 주문 목록에서 삭제한다.
> 1. 주문 완료
> 2. 완료된 주문(CompletedOrder) 인스턴스 생성
> 3. 생성된 CompletedOrder 반환

위 프로세스대로 흘러가면 되지 않을까 싶은데 어떻게 생각하시나요??

2023-10-28 13:52 UTC, BMDK9 commented on src/domain/order/service/store/HandleWaitingOrder.java
> +            } else if (handleNumber != 0) {     // 주문 번호 0번을 입력하지 않았을 때
그 방향으로 구현해보겠습니다!

2023-10-29 11:18 UTC, closed without merging