상품 생성 및 삭제 초안
vanillacake369/sparta-team-kiosk pull request #22
Opened 2023-10-29 12:02 UTC by RyanDJang

상품 생성 및 삭제 초안입니다!

git add . 및 commit 하고 현재까지 진행상황 pull한 다음에, 제가 만든 코드로 브랜치에 push 완료했습니다.

이슈사항 2가지 정도 알려드립니다!

1. 제가 만든 java파일들이 따로할 때는 생성 및 삭제 과정이 잘 돌아가는데, 복붙하니까 이상하게 안 돌아갑니다 ㅠ 원인을 잘 모르겠네요...

2. push 과정은 별 문제 없었는데 보니까 제가 만든 코드에도 import쪽에 api 관련 코드 3줄 정도가 추가되었더라구요!
일단은 놔뒀는데, 없애도 되는 건지 궁금합니다.

+) 아참 그리고 혹시 아까 7시에 회의하셨나요?

디코 알림 뒤늦게 보고 7시에 들어가서 좀 기다렸는데 아무도 안 오시길래 시간이 바뀌었나 해서요 ㅠ

2023-10-29 14:00 UTC, vanillacake369 commented
@RyanDJang 아앗,,, 제가 정신없이 코딩하느라 이제 봤네용!! 
저희 7시에 시간이 나서 잠깐 라이브로 이야기 좀 나누면서 merge 작업헀네용!

2023-10-29 14:04 UTC, vanillacake369 requested changes
전반적으로 로직 흐름이 너무 좋아서,,, 따봉 이빠이 드립니다! 👍 👍 👍 👍 
고생 너무 많으셨습니다!!

다만, StoreProducts에 관련해서 왜 추가해주셨는지만 납득이 잘 안 가네요
설명 부탁드립니다! @RyanDJang

2023-10-29 14:04 UTC, vanillacake369 commented on src/domain/service/storeProducts/StoreProducts.java
> +public class StoreProducts {
오잉? Product가 있는데 혹시 왜 추가하신 건지 여쭤봐도 되나요??

2023-10-29 14:04 UTC, vanillacake369 commented on src/domain/service/createProduct/CreateProductService.java
> +                System.out.println("올바른 가격이 아닙니다. 숫자만 입력하세요.");
오,,,, 가격검증,,,
상당히 좋은 로직 추가해주셨네요

2023-10-29 14:04 UTC, vanillacake369 commented on src/domain/service/productsAdmin/ProductsAdmin.java
> +            }
오,,,, switch문에 예외처리 적용까지,,,,
엄청 많이 늘으셨네요,,,

2023-10-30 00:40 UTC, RyanDJang commented on src/domain/service/storeProducts/StoreProducts.java
> +public class StoreProducts {
오 다행이네요...! 감사합니다ㅎㅎ
앗 merge작업 하셨었군요!
그 때 좀만 더 기다릴 걸 그랬네요...ㅠ

Product.java에서는 Product의 속성을 정의한다고 보면, StoreProducts.java는 좀 디테일하게 보면 상품 생성과 저장만을 담은 메서드를 담은 서비스라서 서로 다른 영역이라고 생각했어요!
가독성을 높이고 패키지화해서 나중에 혹시나 팀적으로 기능을 수정하고 싶을 때 헷갈리지 않게 하고 싶어서 추가했습니다. 개인적으로 팀장님이 생성 서비스와 삭제 서비스를 따로 나눈 자체가 나중에 수정, 보완하기 쉽게 모듈화하는 과정이라고 이해했었어요.
따로 써서 충돌이 일어나는 걸까요?

2023-10-30 00:41 UTC, RyanDJang commented on src/domain/service/createProduct/CreateProductService.java
> +                System.out.println("올바른 가격이 아닙니다. 숫자만 입력하세요.");
실수로 오타 낼 때마다 에러메시지가 떠서 보기 싫어서 구글링해서 추가했어요ㅋㅋ
사실 ~'원'이 자연스럽게 붙어서 나오는 게 좋을 거 같은데, 추가적으로 어떤 식으로 코드를 구성해야 할지 이 부분이 감이 잘 안 오네요ㅠ

2023-10-30 00:43 UTC, RyanDJang commented on src/domain/service/productsAdmin/ProductsAdmin.java
> +            }
이거도 계속 타이핑할 때마다 에러메시지 뜨면서 프로그램이 종료되더라구요!
숫자 외의 키패드를 막아놓을 수도 없고 실제 키오스크에서 그러면 안될 거 같아서 구글링과 chatGPT의 도움으로 했습니다... ㅋㅋㅋ...

2023-10-30 04:01 UTC, vanillacake369 commented on src/domain/service/storeProducts/StoreProducts.java
> +public class StoreProducts {
아하! 근데 고객과 관리자 모두 동일한 상품에 대해서 사용하고, 특히 관리자가 그러한 상품을 생성 및 삭제하는 것이다보니, Product를 쓰는 게 맞겠네요! 이 부분은 제가 merge 이후 수정해서 다시 올릴게요~

2023-10-30 04:01 UTC, vanillacake369 approved these changes

2023-10-30 04:01 UTC, merged

2023-10-30 04:16 UTC, RyanDJang commented on src/domain/service/storeProducts/StoreProducts.java
> +public class StoreProducts {
아 생각해보니 그러네요...!
말씀하신대로 관리자 한 사람이 하는 거니까 굳이 추가로 만들 필요 없을 거 같네요
네 감사합니다ㅎㅎ 고생하셨습니다!