product/cart Update
vanillacake369/sparta-team-kiosk pull request #3
Opened 2023-10-25 01:50 UTC by minhyeongKang

2023-10-25 13:40 UTC, vanillacake369 requested changes

2023-10-25 13:40 UTC, vanillacake369 commented on src/domain/menu/cart/Cart.java
> +    private double sum;
갑자기 의문이 드네요,,,! 카트에 sum이란 속성이 필요할까요,,,! 어떻게 생각하시나요? @minhyeongKang

2023-10-25 13:40 UTC, vanillacake369 commented on src/domain/menu/cart/Cart.java
> +    }
혹시 로직이 어떻게 처리될까요?

2023-10-25 13:40 UTC, vanillacake369 commented on src/domain/menu/cart/Cart.java
>          return;
초기화 로직 구현이 안 되어있네요

2023-10-25 13:52 UTC, vanillacake369 commented on src/domain/menu/cart/Cart.java
> +    private double sum;
카트가 가격합을 계산하는 건 타당하지만, 카트가 가격합을 가지고 있어야할 이유가 있을까 싶어서요
@minhyeongKang

2023-10-25 17:01 UTC, vanillacake369 requested changes
상품 toString() 구현요청

2023-10-25 17:01 UTC, vanillacake369 commented on src/domain/menu/product/Product.java
> +
혹시 상품에 대해서 toString()을 구현해주실 수 있나요?

제가 메뉴에 대한 상품들을 출력해야하는데요
각 상품의 toString()을 모아서 하나의 String으로 만듬으로서 이 기능을 구현할 수 있을 것 같거든요

2023-10-26 00:02 UTC, minhyeongKang commented on src/domain/menu/cart/Cart.java
> +    private double sum;
> 갑자기 의문이 드네요,,,! 카트에 sum이란 속성이 필요할까요,,,! 어떻게 생각하시나요? @minhyeongKang

1차 클래스 설계에 sum이라는 필드값이 명시되어 있어서 넣어 보았습니다..! 빼야할까요?@vanillacake369

2023-10-26 00:40 UTC, vanillacake369 requested changes
추가적으로 구현해주실 부분에 대해서 코멘트 남겨요~

2023-10-26 00:40 UTC, vanillacake369 commented on src/domain/menu/cart/Cart.java
> +        return this.products.toString();
이 구현은 아래와 같이 작동되어서 변경해주셔야 할 거 같아요
```
[ 각 상품객체의 주소값, 각 상품객체의 주소값, 각 상품객체의 주소값, ] 
```

2023-10-26 00:40 UTC, vanillacake369 commented on src/domain/menu/cart/Cart.java
> +    }
1. totalPrice = 0;
2. for문을 통해서 products를 순회하면서 각 product에 접근
3. 각 product의 price값을 가져와서 totalPrice에 합
4. for문을 탈출하고 지역변수 totalPrice를 반환

2023-10-26 03:16 UTC, vanillacake369 requested changes
2차 수정 부탁드립니다.

2023-10-26 03:16 UTC, vanillacake369 commented on src/domain/menu/product/Product.java
> +    private static int id = 1;
`private int id;`

2023-10-26 03:16 UTC, vanillacake369 commented on src/domain/menu/product/Product.java
> +        return ++id;
return id;

2023-10-26 03:16 UTC, vanillacake369 commented on src/domain/menu/product/Product.java
> +    }
```
 Product(int id,String name, double price, String description) {
        this.id = id;
        this.name = name;
        this.price = price;
        this.description = description;
    }
```

2023-10-26 04:33 UTC, minhyeongKang commented on src/domain/menu/cart/Cart.java
> +        return this.products.toString();
이부분 수정중인데,,아래와 같이 작성한 코드는 어떤 것 같으신가요?
```
@Override
    public String toString() {
        return String.format("%s\n", products);
    }
```

2023-10-26 04:35 UTC, minhyeongKang commented on src/domain/menu/cart/Cart.java
> +    }
이렇게 작성해보았습니다.
```
public double getTotalPrice() {
        double totalPrice = 0.0;

        for (Product product : products) {
            totalPrice = product.getPrice() + totalPrice;
        }
        return totalPrice;
    }
```

2023-10-26 04:35 UTC, minhyeongKang commented on src/domain/menu/cart/Cart.java
>          return;
초기화 관련하여 리스트 덮어씌우는 형태로 작성해 보았어요.
```
public void clear() {
        products = new ArrayList<>();
    }
```

2023-10-26 04:43 UTC, vanillacake369 commented on src/domain/menu/cart/Cart.java
> +        return this.products.toString();
@minhyeongKang 음,,,그것보다는 products가 List형태이다보니까 순회하면서 출력하면 좋을 거 같아요

2023-10-26 04:44 UTC, vanillacake369 commented on src/domain/menu/cart/Cart.java
>          return;
엇,,, 값을 비워주는 함수이기 때문에 새로 선언해주시면 안 됩니다!!

2023-10-26 06:25 UTC, merged